[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[dev]
  command = "npm start"

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/portfolio"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/services"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
